print("Hello, World!")
print("irtiza_hassan")
print("1,2,3,4,5")
print("Hello \nWorld")
print("Hello \tWorld")
print("apple" "banana" "pickle",sep=",")
print(1,2,3,sep="-")
print("Hello" , "World")
print(1,end="")
print(2)
print('He said,"Hello!"')
print("Its name is backslash:\\")
print("I am 15 years old")
print("The number is 0.21")
for i in range(1,6):
    print(i)